### ISSUE TITLE
Incorrect values returned for mutliple tag queries on same measurement

### ISSUE THREAD

**Issue by pkittenis** [InfluxGraph/influxgraph#14]
Identical values are returned, overriding each other.

**Comment by pkittenis** [comment]
Hi @tulanian,

Could you please give this [branch](https://github.com/InfluxGraph/influxgraph/compare/multi_tmpl_tags_no_fields_test) a go? Now see the below from this [test case](https://github.com/InfluxGraph/influxgraph/commit/fe9276f8798b4077be57b9125d486272488210f5):

![multi_query6](https://cloud.githubusercontent.com/assets/1391208/20972666/8a1ae4da-bc8d-11e6-9442-6f9b18d5d455.png)

**Comment by tulanian** [comment]
Looks a lot better! Getting multiple graphs now.

**Comment by pkittenis** [comment]
Cool, just making sure the test case is accurate :) This fix will be in next RC.
