### ISSUE TITLE
No handlers could be found for logger "influxgraph" 

### ISSUE THREAD

**Issue by julienmary** [InfluxGraph/influxgraph#22]
Hi,
I run under ubuntu 16.04, using nginx and uwsgi to connect to graphite-api
All the services are starting, anyway uwsgi complains that : 

> No handlers could be found for logger "influxgraph" 

I have carrefully followed instructions for the install. What kind of info can I provide to help to sort this out ?

Julien

**Comment by pkittenis** [comment]
That message is printed by the Python interpreter when something is logged without handlers for the logger used. It is not a bug.

Logging configuration is off by default. It may be left like that or logging configuration added to config per the [example config file](https://github.com/InfluxGraph/influxgraph/blob/master/graphite-api.yaml.example#L15-L22).

**Comment by julienmary** [comment]
OK. Thanks.
When I try url http://localhost:9999/dashboard/find 
it's ending into timeout and bad gateway, so I still need to investigate that ... I'm not very familiar with that stack, sorry to have disturbed for something not related.

**Comment by pkittenis** [comment]
The docker container may be used for an out of the box working graphite api and influxgraph service. The above does not look like a Graphite API call so can't comment.

**Comment by julienmary** [comment]
I finally made it work and I can now get svg from command line to automate the creation of LaTeX files for reporting. 

Thanks for this awesome work. What you did is essential for my present mission.

**Comment by pkittenis** [comment]
Glad it works well for you. Admittedly that particular use case is not something I had considered before though it's interesting - might have a use for it in future. Thank you for the feedback.

**Comment by julienmary** [comment]
That's the genious of open source ... you publish, you can't imagine what it will become ... :-)
