### ISSUE TITLE
Umm. am I an idiot?!

### ISSUE THREAD

**Issue by seanvree** [InfluxGraph/influxgraph#28]
So I am a BIT noobish to Graphite, but not to python or Influx.  

I cloned the repo....great. 

Ran python setup.py install....great.

So...how do I run this? All I see is Versioneer.py???

**Comment by deniszh** [comment]
You need to install [graphite-api](https://graphite-api.readthedocs.io/en/latest/installation.html) and change [example config](https://github.com/InfluxGraph/influxgraph/blob/master/graphite-api.yaml.example) for it to match your setup.

**Comment by seanvree** [comment]
@deniszh  - Right, Which I did, but how do I actually run influxgraph?

Paths:
influxdb: c:\influxd
influxgraph:c:\influxgraph

**Comment by deniszh** [comment]
You don't need to run it. Run graphite-api, it will call InfluxDB with help of influxgraph.

**Comment by deniszh** [comment]
If you asking about data ingestion - influxgraph not doing that, it's only getting data from influxdb. Use usual Influxdb Graphite input - https://github.com/influxdata/influxdb/blob/master/services/graphite/README.md

**Comment by seanvree** [comment]
@deniszh - Yeah, I got that, but again, I don't understand how to run graphite-api? 

I have Influx running with a Graphite Db set up and a listener on port 2003.  I guess I"m not understanding how to invoke the API calls to Influx??

**Comment by deniszh** [comment]
You need to run Graphite-api, its docs have some ways how to do so - https://graphite-api.readthedocs.io/en/latest/deployment.html
Usually, Gunicorn + nginx is simplest.

**Comment by pkittenis** [comment]
Hi,

For an out of the box service with all required bits and default configuration see the docker container instructions on the front page. To paraphrase:

```
docker pull ikuosu/influxgraph
docker create  --name=influxgraph -p 8000:80 ikuosu/influxgraph
docker start influxgraph
```

> There will now be a Graphite-API running on localhost:8000 from the container with a default InfluxDB configuration and memcache enabled. Finder expects InfluxDB to be running on localhost:8086 by default.

To use it you use the Graphite API on that port as usual - influxgraph then handles the API calls to influx.

For self-installation, see [Graphite-API documentation](https://graphite-api.readthedocs.io/en/latest/deployment.html) per above.
