### ISSUE TITLE
multiple target query fails with IndexError

### ISSUE THREAD

**Issue by ernsy** [InfluxGraph/influxgraph#32]
I populated my influxdb with:

    > insert test,stat=count value=1 
    > insert test,stat=upper_90 value=10 
    > insert test2,stat=count value=20 
    > insert test2,stat=upper_90 value=15 

Then using grafana the following query is produced:

    target=test.count
    &target=test2.upper_90
    &from=1495610419&until=1495610636&format=json&maxDataPoints=1912

the data is then returned as:

test.count = 10 where it should be 1
test.upper_90 is correct

My template is:

    - "measurement.stat"

From my trace the query to influxdb is:

    /query?q=select mean("value") as "value" from "test", "test2" where (time > 1495610419s and time <= 1495610636s) AND (("stat" = 'count' OR "stat" = 'upper_90')) GROUP BY time(10s), "stat" fill(previous)&epoch=s&db=stats

**Comment by pkittenis** [comment]
What are the timestamps for the inserted data? Can show output of `select *` on the measurements.

Whether or not the `1` value would be included in data depends on its timestamp - the query has a defined start and end time less than 3 minutes apart.

Can also see the data being selected with a query like

`select * from "test", "test2" where (time > 1495610419s and time <= 1495610636s) AND (("stat" = 'count' OR "stat" = 'upper_90'))`

**Comment by ernsy** [comment]
@pkittenis yes the 1 value is within the the range with timestamp `1495610437`

    > select * from "test", "test2" where (time > 1495610419s and time <= 1495610636s) AND (("stat" = 'count' OR "stat" = 'upper_90'))
    name: test
    time                count stat     upper_90 value
    ----                ----- ----     -------- -----
    1495610437236090553       count             1
    1495610466428242949       upper_90          10
    
    name: test2
    time                count stat     upper_90 value
    ----                ----- ----     -------- -----
    1495610520939419483       upper_90          15
    1495610533354781440       count             20

**Comment by pkittenis** [comment]
Yes, have been able to replicate.

The issue is the template configuration is generating overly broad queries that return data that was not requested.

The influx query is returning data for `test stat=count`, `test stat=upper_90`, `test2 stat=count` and `test2 stat=upper_90` as `stat` is configured in the template as a tag, hence is used in the group by clause and in addition both tag values were requested that exist in both measurements.

If you run the generated influx query with the `group by`, you will see four sets of data, not two. Since that is the template configured and data in the DB, there is not anything influxgraph can do here. The template configuration will need to be adjusted to fit the data and vice versa.

Specifically, use fields instead of trying to select on tag values. 

Tags are for indexed data, things to either select with or group on. While the template syntax allows for not having fields, and influxgraph's implementation is identical to influx so it allows it also, the data will need to be appropriate for that or you'll get unexpected results.

Eg:

Template: `"measurement.field"`

```
> insert test count=1 
> insert test upper_90=10 
> insert test2 count=20 
> insert test2 upper_90=15 
```

Any combinations of `test.*`, `test2.*` work fine.

See also influxdb documentation on using fields.

**Comment by pkittenis** [comment]
@ernstroux - does that make sense and work for you?

**Comment by ernsy** [comment]
Yes, however it doesn't seem to work. The query to influx is invalid:

/query?q=select mean("count") as "count" from "test" where (time > 1495527732s and time <= 1495700532s) **AND ()** GROUP BY time(60s) fill(previous)&epoch=s&db=stats

But that is probably a separate issue however not sure that this approach will always work, what if you have another tag and your template is `measurment.foo.field` with the following data:

    > insert test,foo=bar count=1,upper_90=10
    > insert test,foo=baz count=2,upper_90=11
    > insert test2,foo=bar count=20,upper_90=15
    > insert test2,foo=baz count=21,upper_90=16

And you query:

  
    target=test.bar.count
    &target=test2.baz.upper_90
    &from=-7d&until=now&format=json&maxDataPoints=1920

The query to influx is then similar to 

`select mean("count") as "count", mean("upper_90") as "upper_90" from "test", "test2" where (time > 1495784083s and time <= 1495784383s) AND (("foo" = 'bar' OR "foo" = 'baz')) GROUP BY time(300s), "foo" fill(previous)&epoch=s&db=stats`

which returns:

	time                count upper_90
	----                ----- --------
	1495783800000000000       
	1495784100000000000 1.5   10.5
	
	name: test2
	time                count upper_90
	----                ----- --------
	1495783800000000000       
	1495784100000000000 20.5  15.5

 but we are expecting test.bar.count=1 and test2.baz.upper_90=16

The influxgraph query then fails with:

      File "/opt/influxgraph/local/lib/python2.7/site-packages/influxgraph/utils.py", line 231, in read_influxdb_values
    metric = measurement_data[measurement]['paths'][m_path_ind]
    IndexError: list index out of range

So two different issues here, the query to influx will need to change and matching on the data returned to influxgraph will probably need to be done

Our reason for trying influxgraph is to attempt maths across different metrics in influx, as it is not yet implemented in influx, but we might move to another DB, otherwise if we decide to use influxgraph I'll need to sharpen up my python skills

**Comment by pkittenis** [comment]
That is a different issue, the above should work.

The influx query and data returned are correct as far as I can see. The means of `[1,2]` and `[15,16]` are `1.5` and `15.5` respectively, so why would you expect `1` and `16`? The aggregation function can be configured to something else if `mean` is not wanted.

A single query `target=test*.bar.{count,upper_90}` works in the mean time. There's no need to use separate queries when the paths are common among targets and response times are faster when not.

![query](https://cloud.githubusercontent.com/assets/1391208/26626910/96b25d30-45f0-11e7-964d-3736925e701c.png)

**Comment by pkittenis** [comment]
`1.3.5` release contains fixes for the two issues found here, please check.

Regarding the data returned that you mentioned, the influx query looks correct and data looks like the below, not what I mentioned before. Note the group by `foo` tag and separate values per tag on each measurement.

`select mean("count") as "count", mean("upper_90") as "upper_90" from "test", "test2" where time > now() - 10m AND (("foo" = 'bar' OR "foo" = 'baz')) GROUP BY time(300s), "foo"`

```
name: test
tags: foo=bar
time                count upper_90
----                ----- --------
1496331600000000000       
1496331900000000000 1     10
1496332200000000000       

name: test
tags: foo=baz
time                count upper_90
----                ----- --------
1496331600000000000       
1496331900000000000 2     11
1496332200000000000       

name: test2
tags: foo=bar
time                count upper_90
----                ----- --------
1496331600000000000       
1496331900000000000 20    15
1496332200000000000       

name: test2
tags: foo=baz
time                count upper_90
----                ----- --------
1496331600000000000       
1496331900000000000 21    16
1496332200000000000       
```

**Comment by ernsy** [comment]
Thanks, did some quick tests and the issues seems resolved. We are going to use non-default fields going forward as Influxgraph handles it better.
