### ISSUE TITLE
Auto-conversion of tag values containing dots

### ISSUE THREAD

**Issue by sesto** [InfluxGraph/influxgraph#33]
Tags that contain dot-separated values, for example ```instance=172.16.179.252:8080``` are not handled correctly upon loading from InfluxDB.  When such metrics are fed to graphite via carbon,  they are automatically converted to ```instance=172%2E16%2E179%2E252:8080``` and further handled correctly. I would expect the same behaviour from influxgraph.

**Comment by pkittenis** [comment]
Hi there, thanks for the interest.

InfluxGraph does not handle ingestion. Influxdb does not do any conversion of data, unlike carbon, so the data fed into it will need to be named appropriately prior to ingestion if they are to be exposed via the Graphite API. The above also breaks influxdb's graphite service templates when fed data via graphite line protocol.

Will leave this open as a new feature to automatically convert dots in tag values to a _configurable_ character if someone is keen to work on it.
