### ISSUE TITLE
Docker: make memcache max value configurable

### ISSUE THREAD

**Issue by tux1337** [InfluxGraph/influxgraph#53]
I found no way to configure the memcache max value size in the official docker container. 

We have a really large InfluxDB and have to increase the max value size (Parameter -I) to prevent following error message:
>[ERROR] 2018-09-13 11:23:47,245 - finder.get_field_keys() - Could not add field key list to memcache - likely field list size over max memcache value

Change of /etc/default/memcached with MAXITEMSIZE="128m" has no effect, 
also /etc/memcached.conf to -I 128m has no effect.
I guess the two files are ignored when the memcached service is not started over /etc/init.d/memcached as it is done with the own startup script memcached.sh.

So I changed the memcached.sh Script:
>#!/bin/sh
>exec /sbin/setuser memcache /usr/bin/memcached -I 128m -v >>/var/log/memcached.log 2>&1

My suggestion is to make the parameter configurable over an environment variable. Maybe it is possible to export the value from the graphite-api.yml and use them also for startup of memcached
>  memcache:
>    host: localhost
>    max_value: 128

What do you think about this? Am I wrong in one point?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Yes, that all sounds accurate. Making the memcached.sh script use `/etc/memcached.conf` config and have override in the config might be more appropriate, and would also allow for config overriding in containers for changing other memcached settings.

But either solution would be fine if you'd like to make a PR for it.

**Comment by tux1337** [comment]
Should not be a big deal if we use the init script with memcached.conf
memcached.conf must be changed to ensure that we get the log file to the right place
The memcached.sh file could be replaced with: 
`/etc/init.d/memcached start`
or we execute this command in the memcached.sh file to prevent that we have to change the run mechanism. 

I will try to make a PR

**Comment by pkittenis** [comment]
```
The memcached.sh file could be replaced with:
/etc/init.d/memcached start
```

No, it cannot. The container base image does not use init.d, hence why none of the service use it. The `memcached.sh` script can have memcached read configuration from the standard `/etc/memcached.conf` though.

**Comment by tux1337** [comment]
I implemented today some changes in memcached.sh and provided an example /etc/memcached.conf. Looks good.
I will test this tomorrow again and submit an PR

**Comment by tux1337** [comment]
please see PR #54 

I've also pushed the docker image build with the changes to docker hub for testing purposes: 
https://hub.docker.com/r/tux1337/influxgraph/

Maybe someone can update the official one after merge.

**Comment by tux1337** [comment]
PR #54 is merged.

It is now possible to configure memcache with /etc/memcached.conf
