### ISSUE TITLE
Segfaults on building the index

### ISSUE THREAD

**Issue by tulanian** [InfluxGraph/influxgraph#57]
Running Influxgraph 1.5.0

Started getting segfaults yesterday during index creation. Pretty sure it's choking on one or more bad series, but there are over 150,000 of them. I'll attach a debug dump from gunicorn/graphite-api.  The segfault appear to happen when the initial series data is passed to parse_series() at classes/finder.py:566.

As I don't know what data is causing the problem I'm looking for help on determining that.

**Comment by tulanian** [comment]
[dump.txt](https://github.com/InfluxGraph/influxgraph/files/2515012/dump.txt)

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report.

That's interesting, can you upload output of `show series` and `show templates` respectively from the database in a couple files? It looks like it is segfaulting on parsing templates - will need template values to reproduce.

**Comment by iridos** [comment]
I think I am seeing the same. And it seems to be caused by the following return lines from SHOW SERIES:
temp,dc=blubb,host=n0712,jobId=33624,nodes=1,ppn=16,reqResources=neednodes\=1:ppn\=16\,nodes\=1:ppn\=16\,walltime\=1201:00:00,sensor=coretemp_core7_max,user=ul_l_a,walltime=1201:00:00

**Comment by cout** [comment]
I ran into the same problem when I installed influxgraph from pip (verion 1.5.0).  After rebuilding from source, I no longer see a segfault building the index.
