### ISSUE TITLE
Updates of Docker Image

### ISSUE THREAD

**Issue by tux1337** [InfluxGraph/influxgraph#58]
The docker image that is mentioned in the readme seems to be unmaintained: ikuosu/influxgraph

The last push to Docker Hub was with the release of 1.3.7 one year ago.
Are there any plans to change this situation?

In my opinion the best would be an automated build triggered on new releases and updates of the baseimage used in the dockerfile. Ideally as a repo Influxgraph/Influxgraph, the own Namespace is more trustworthy.

**Comment by pkittenis** [comment]
Hi there,

Docker builds are already automatic on tags, hence why it has not been updated since last release. Will release a new tag to get it updated.

Yes, I agree it would be better to have a named repo - and would prefer a top level repo like just `influxgraph` which is a little more involved.

@tux1337 - would you be up for being added as a maintainer to this project?

**Comment by tux1337** [comment]
Is the automated build for the docker image done over travis-ci? 

If there is something that I can do I would support this project as maintainer...

**Comment by pkittenis** [comment]
Yes, [run via travis](https://github.com/InfluxGraph/influxgraph/blob/master/.travis.yml#L90-L99) for master branch (latest) and on pypi releases (tags).

There were a couple bugs in the travis cfg and tags had not been updated for a while, have fixed those. Have also moved the docker hub repo to `influxgraph/influxgraph` and added your username to that organisation as well as to the one for this repo.

Should now have access to merge and push to both.

**Comment by tux1337** [comment]
Great, Sounds good. 

I will prepare an update for the readme and example files with the new repo Information and will make a PR for review. 
At the moment I test an build with the latest phusionbaseimage which is based on Ubuntu 18.04 LTS, PR will also follow.
